### ISSUE TITLE
Unstable sorting

### ISSUE THREAD

**Issue by 616slayer616** [paour/natorder#8]
https://github.com/paour/natorder/blob/ab9e2dfd165736a90f3d8784e76c906e6603db52/NaturalOrderComparator.java#L112-L116

As the comment indicates this leads to unstable behavior.

Shuffling like this:
`Collections.shuffle(input, new Random(3000));`

Will have a different result from not shuffling the input.

The problem can be demonstrated with these tests:

```
@Test
void differentLengthEquality() {
    int compare = naturalOrderComparator.compare("1-2", "1-02");
    int compare2 = naturalOrderComparator.compare("1-02", "1-2");

    assertTrue(compare < 0);
    assertTrue(compare2 > 0);
}

@Test
void sameLengthEquality() {
    int compare = naturalOrderComparator.compare("pic 5", "pic05");
    int compare2 = naturalOrderComparator.compare("pic05", "pic 5");

    assertTrue(compare < 0);
    assertTrue(compare2 > 0);
}

@Test
void zero() {
    int compare = naturalOrderComparator.compare("pic010", "pic 010");
    int compare2 = naturalOrderComparator.compare("pic 010", "pic010");

    assertTrue(compare < 0);
    assertTrue(compare2 > 0);
}
```

A possible solution would be this:

```
private int compareEqual(String a, String b, int nza, int nzb) {
        if (nza - nzb != 0)
            return nza - nzb;

        if (a.length() == b.length())
            return a.compareTo(b);

        return a.length() - b.length();
}
```

and replacing the mentioned line with 
```
if (ca == 0 && cb == 0) {
                // The strings compare the same. Use other means of comparison
                return compareEqual(o1, o2, nza, nzb);
}
```

**Comment by paour** [comment]
Thank you for the detailed descriptions and PRs!

**Comment by 616slayer616** [comment]
Thank your for the great implementation.

I have not found anything working remotely as well as yours!

Ans I'm excited to help and be a part of this project

**Comment by paour** [comment]
Thank you. I merely ported an existing solution to Java, a very long time ago (if the code style doesn't make that painfully clear :-) ).
